AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Overview-connectDashboard

Parameters:
  ProjectName:
    Type: String
    Default: MvpConnectInstances
    Description: A prefix that will be applied to all resources in the stack. Required.
  CrossAccountTableNameParameter:
    Type: String
    Default: itsmorse-mc-infrastructure-CrossAccountTable
    Description: The table that contains data about cross account
  DefaultRegionParameter:
    Type: String
    Default: us-east-1
    Description: The default region of AWS-ACCOUNT of Morse
  CompanyConnectInstancesParameter:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /itsmorse-mc-infrastructure/dynamodb/CompanyConnectInstances/TableName
  CrossAccountParameter:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /itsmorse-mc-infrastructure/dynamodb/CrossAccountTable/TableName
  CrossAccountStream:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /itsmorse-mc-infrastructure/dynamodb/CrossAccountTable/StreamArn

Resources:
  InjectionInstancesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-InjectionInstances"
      CodeUri: injection-instances/injection-instances.zip
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 900
      MemorySize: 1024
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBStreamReadPolicy: 
            TableName: !Ref CrossAccountParameter
        - DynamoDBCrudPolicy:
            TableName: !Ref CrossAccountParameter
        - DynamoDBCrudPolicy:
            TableName: !Ref CompanyConnectInstancesParameter
      Events:
        DynamoDBEvent:
          Type: DynamoDB
          Properties:
            Stream: !Ref CrossAccountStream
            StartingPosition: LATEST
            BatchSize: 1
      Environment:
        Variables:
          DEFAULT_REGION: !Ref DefaultRegionParameter
          TABLE_NAME: !Ref CompanyConnectInstancesParameter

Outputs:
  DashboardInjectionInstancesFunction:
    Description: "Lambda Function ARN for InjectionInstances"
    Value: !GetAtt InjectionInstancesFunction.Arn